"""empty message

Revision ID: 139c40e5a12f
Revises: 9f503333d2b2
Create Date: 2021-12-29 13:15:16.670121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139c40e5a12f'
down_revision = '9f503333d2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('cotent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cotent', sa.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
