"""empty message

Revision ID: 687fa2d50cf0
Revises: c9b29823db78
Create Date: 2021-12-22 21:38:41.527472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687fa2d50cf0'
down_revision = 'c9b29823db78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
